---
language: node_js
node_js:
  - "8"

sudo: required
dist: trusty


branches:
  only:
    - master

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

matrix:
  include:
    - env: PREMBER_VERSION="v1.10.0"
    - env: PREMBER_VERSION="v1.11.0"
    - env: PREMBER_VERSION="v1.12.0"
    - env: PREMBER_VERSION="v1.13.0"
    - env: PREMBER_VERSION="v2.0.0"
    - env: PREMBER_VERSION="v2.1.0"
    - env: PREMBER_VERSION="v2.2.0"
    - env: PREMBER_VERSION="v2.3.0"
    - env: PREMBER_VERSION="v2.4.0"
    - env: PREMBER_VERSION="v2.5.0"
    - env: PREMBER_VERSION="v2.6.0"
    - env: PREMBER_VERSION="v2.7.0"
    - env: PREMBER_VERSION="v2.8.0"
    - env: PREMBER_VERSION="v2.9.0"
    - env: PREMBER_VERSION="v2.10.0"
    - env: PREMBER_VERSION="v2.11.0"
    - env: PREMBER_VERSION="v2.12.0"
    - env: PREMBER_VERSION="v2.13.0"
    - env: PREMBER_VERSION="v2.15.0"
    - env: PREMBER_VERSION="v2.16.0"
    - env: PREMBER_VERSION="v2.17.0"

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - secure: "fdqVSvxFTeaJh30iChsKb6GDCJP1lMFIvyaOdE5X9Krkck+LTMPo6pzSLiSYTxeMZMnE/Cd7j/FxtKvj4bxiWtnrq4mW6ytnJKybvUMtKlB506w/ORoRWj0TDQuU8Gvn7i1l70ekAqcBPxhkhNfxQ0iJV0J2YHpa+BCIE5z4a9HB+QZJXijFkE7QOUdtHRyQBk0MvWHc3XNRMaFRVNblzNvoVfP3l5x35uzmC7cI4DUtDlDmrUhOxHzz3X9TUnzaxdo5S3GjZfYTpu1UDZmKgQHfEf6r7TS976HBzsCKRM2qXTb6q0ijT+4MFsT5FkIrSawW6OXvlNBmqpTx55/FLeJBUzjaNTQZxipedppcMk2wm0IVDKjxHhGJE6RzjUKqeE+HodYLyiuNHTuR6CROAGfQO0t/yL/yXff7qsbTlOamQkuOGhCjd15hb9JJYVWiqFRvYjc1PcBvon/afHz9U2qR04E9u1vt9ytc/PVd7TXVWSlCHOC9KJj68qwvpW+qRJNrCl9kz9WxEzh1ZeSIGwnKbRm40HXbgi4gUOExqxExapcmNPSqCTjthc4iCBQlH/kmeD7pqOw8MVs5tyo9uQ5BJl0x9tI58Y37TzL35/9mxJ5B6l0IOmRhKYhoRMAvhmxgyUyIkmMYkyzREmkGJNmPj/O+vsfmivO4Qz9DUJ4="

before_install:
  - npm install -g npm@5
  - npm config set spin false

script:
  - npm run lint:js
  - npm test
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ember deploy production --activate fi'
