---
language: node_js
node_js:
  - "8"

sudo: required
dist: trusty

branches:
  only:
    - master

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - secure: qoD5AxH2LcHYhbYDvorNtvci+u3VVbpGHT1LHIKny6P2v0QKoOEJz5o6liWHom8V5Rj4MO/LLUipMPo0Xi18HycWJxRNZIWzPOUzq1lpwPqN4F3qRWtyEuuSbECY34GEoOOFhzOivXuOkmpWSGY2UWYTCmWXuNKJh4bRmX/iPnhUj6SI7+atj75aCeJ0ckWJfv/NYGlelK2eWoixoQCeKtM9EpWR3ZwATJeV0PSVLLgPGHP/dW2U8pUGvzSu4+9v7EClemLG/6rBsJAFI3znAitpgjV76oGt2MaxMr4eRhO05j5h3I88DSjarRjMTmx33bM1+kQdCNI+tlmFQ2sYSReMfv5oN8lfS2eK8tLIiVGJk+lcQZ4MhRPcU4xUeUb6h36uYi0ho5ydN3MewZLGSLld7CmhRo6zPJlOiY6e4lfxBQxtZABGhYcK3AKSDN0Mf2mEeDDjCk4pKCkfuNRiimbc9B6+UNqxjHuWu6ALpEaOl0WZhs7AOcVJkPDKOVI4jIeg06uCaedX0uIf+w+/Vkf0up1Kdx3bCCKL6/lx4oSRqv/KyT3f1XVXbeJ/l6O81rXOT2FW+jo9Q56XS1Y8qKIUpOS9of84l91U8VEf+nTced8PjKkosJgaexVLe/K5Q4BoxJDAqoNIbkwRF5QisoBCWn2BF6Hky//50XT5Zfs=
before_install:
  - npm install -g npm@5
  - npm config set spin false

jobs:
  include:
    - stage: test
      script:
        - npm run lint:js
        - npm test
    - stage: Staging Deployment
      if: branch = master AND NOT type = pull_request
      script: ember deploy production --activate
